apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-cni-default
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "mode": "bridge",
      "master": "eth0",
      "name": "macvlan-cni-default",
      "ipam": {
        "type": "spiderpool"
      }
    }'
