apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-ippool-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      annotations:
        ipam.spidernet.io/ippool: |-
          {
            "ipv4": ["static-ipv4-ippool"]
          }
      labels:
        app: static
    spec:
      containers:
        - name: static-ippool-deploy
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
