apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-default-subnet-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-default-subnet-deploy
  template:
    metadata:
      labels:
        app: cluster-default-subnet-deploy
    spec:
      containers:
        - name: demo-deploy-subnet
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
